<x-chart-layout title="Network statistics from {{ $systemName }}" hostPath="{{ $hostPath }}">
    <h1>Network statistics from {{ $systemName }}</h1>
    <x-chart-tip-layout></x-chart-tip-layout>
    <div data-netdata="net.pppoe0"
         data-chart-library="easypiechart"
         data-title="pppoe0 Net Inbound"
         data-dimensions="received"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="net.pppoe0"
         data-chart-library="easypiechart"
         data-title="pppoe0 Net Outbound"
         data-dimensions="sent"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="net.eth4.500"
         data-chart-library="easypiechart"
         data-title="TM VLAN Net Inbound"
         data-dimensions="received"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="net.eth4.500"
         data-chart-library="easypiechart"
         data-title="TM VLAN Net Outbound"
         data-dimensions="sent"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="net.eth4"
         data-chart-library="easypiechart"
         data-title="WAN Physical Net Inbound"
         data-dimensions="received"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="net.eth4"
         data-chart-library="easypiechart"
         data-title="WAN Physical Net Outbound"
         data-dimensions="sent"
         data-width="200"
         data-height="200"
         data-after="-600"
         data-points="600"
    ></div>
    <div data-netdata="system.cpu"
         data-dygraph-valuerange="[0, 100]"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="net.pppoe0"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="net.eth4"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="net.eth4.500"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_10_55_48_24_rtt"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_10_55_100_246_rtt"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_2001_e68__b_42_rtt"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_2001_e68__b_4014_rtt"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_10_55_48_24_packet_loss"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_10_55_100_246_packet_loss"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_2001_e68__b_42_packet_loss"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
    <div data-netdata="ping_ISP_Edge.host_2001_e68__b_4014_packet_loss"
         data-chart-library="dygraph"
         data-width="90%"
         data-height="200"
         data-after="-600"
    ></div>
</x-chart-layout>
